### ISSUE TITLE
Collections 1.9.1+ bigip_command fails with 'AnsibleModule' object has no attribute 'provider'

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [F5Networks/f5-ansible#2061]
##### COMPONENT NAME

f5networks.f5_modules.bigip_command
 

##### ANSIBLE VERSION

```
[root@Elysium provisioner]# ansible --version
ansible [core 2.11.2] 
  config file = /git/workshops/provisioner/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 2.11.2
  libyaml = False
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.4
  Build       0.0.6
  Edition     Point Release 4
  Date        Thu Jun 18 20:31:45 PDT 2020
```
##### SUMMARY

In Collections 1.9.1 and 1.10.0 using bigip_command fails to complete tasks with object has no attribute 'provider'

##### STEPS TO REPRODUCE

```
- name: Change BIG-IP F5 mgmt password
  f5networks.f5_modules.bigip_command:
    provider:
      ssh_keyfile: "{{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
      transport: cli
      user: admin
      server: "{{ ansible_host }}"
    commands: "modify auth user admin password {{ admin_password }}"
  register: change_password
  until: change_password is not failed
  retries: 5
  delay: 10
```

Code was tested from playbooks of Ansible Workshops https://github.com/ansible/workshops

Building this in a UDF image that can be used if needed.

##### EXPECTED RESULTS

Completes password Reset and moves to next lines

##### ACTUAL RESULTS

```
FAILED - RETRYING: Change BIG-IP F5 mgmt password (1 retries left).Result was: {
    "attempts": 5,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1624575446.6890724-8607-142366878053362/AnsiballZ_bigip_command.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1624575446.6890724-8607-142366878053362/AnsiballZ_bigip_command.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1624575446.6890724-8607-142366878053362/AnsiballZ_bigip_command.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_jeso0e8b/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 740, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_jeso0e8b/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 733, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_jeso0e8b/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 663, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_jeso0e8b/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 589, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_jeso0e8b/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 130, in send_teem\nAttributeError: 'AnsibleModule' object has no attribute 'provider'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "retries": 6
}
<34.214.65.78> using connection plugin network_cli
redirecting (type: connection) ansible.builtin.persistent to ansible.netcommon.persistent
<34.214.65.78> EXEC /bin/sh -c 'echo ~root && sleep 0'
<34.214.65.78> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860 `" && echo ansible-tmp-1624575458.1589723-8607-251674335974860="` echo /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
<34.214.65.78> PUT /root/.ansible/tmp/ansible-local-66126xjkvip3/tmpid37oqpv TO /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py
<34.214.65.78> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/ /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py && sleep 0'
<34.214.65.78> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py && sleep 0'
<34.214.65.78> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 740, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 733, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 663, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 589, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 130, in send_teem
AttributeError: 'AnsibleModule' object has no attribute 'provider'
fatal: [F5-RH-Provisioner-UDF-student1-f5]: FAILED! => {
    "attempts": 5,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1624575458.1589723-8607-251674335974860/AnsiballZ_bigip_command.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 740, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 733, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 663, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 589, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_secv5s4_/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 130, in send_teem\nAttributeError: 'AnsibleModule' object has no attribute 'provider'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

**Comment by VDI-Tech-Guy** [comment]
Validated same issue occurs using password instead of ssh_keyfile in provider.

Works fine in 1.9.0 
Fails in 1.9.1+


TASK [Change BIG-IP F5 mgmt password] ************************************************************************
task path: /git/Testbed-Roles/testbed.yaml:19
<10.192.1.140> Using network group action f5networks.f5_modules.bigip for f5networks.f5_modules.bigip_command
Loading collection ansible.netcommon from /root/.ansible/collections/ansible_collections/ansible/netcommon
<10.192.1.140> connection transport is cli
<10.192.1.140> using connection plugin network_cli
redirecting (type: connection) ansible.builtin.persistent to ansible.netcommon.persistent
<10.192.1.140> starting connection from persistent connection plugin
Found ansible-connection at path /usr/local/bin/ansible-connection
<10.192.1.140> local domain socket does not exist, starting it
<10.192.1.140> control socket path is /root/.ansible/pc/57ec90ee02
<10.192.1.140> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
<10.192.1.140> Loading collection ansible.netcommon from /root/.ansible/collections/ansible_collections/ansible/netcommon
<10.192.1.140> redirecting (type: terminal) ansible.builtin.bigip to f5networks.f5_modules.bigip
<10.192.1.140> Loading collection f5networks.f5_modules from /root/.ansible/collections/ansible_collections/f5networks/f5_modules
<10.192.1.140> local domain socket listeners started successfully
<10.192.1.140> unable to load cliconf for network_os bigip
<10.192.1.140> 
<10.192.1.140> local domain socket path is /root/.ansible/pc/57ec90ee02
<10.192.1.140> socket_path: /root/.ansible/pc/57ec90ee02
<10.192.1.140> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<10.192.1.140> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<10.192.1.140> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.192.1.140> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.192.1.140> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006 `" && echo ansible-tmp-1624590302.4966748-17522-248580353826006="` echo /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
<10.192.1.140> PUT /root/.ansible/tmp/ansible-local-175139h9858ia/tmp3ydgnhmh TO /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py
<10.192.1.140> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/ /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py && sleep 0'
<10.192.1.140> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py && sleep 0'
<10.192.1.140> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 740, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 733, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 663, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 589, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 130, in send_teem
AttributeError: 'AnsibleModule' object has no attribute 'provider'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1624590302.4966748-17522-248580353826006/AnsiballZ_bigip_command.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 740, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 733, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 663, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 589, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_v4ctidbx/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 130, in send_teem\nAttributeError: 'AnsibleModule' object has no attribute 'provider'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by wojtek0806** [comment]
This is a known issue only if you use CLI as transport, for both bigip_wait and bigip_command will fix that shortly

**Comment by wojtek0806** [comment]
collection 1.10.1 with the fix on galaxy
