### ISSUE TITLE
bigip_command module fails with AttributeError: 'module' object has no attribute 'ANSIBLE_CONNECTION_PATH'

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1302]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### CONFIGURATION

How does one tell the version of the role?
install_date: Thu Apr 25 00:46:55 2019
version: master
##### OS / ENVIRONMENT

Ubuntu 18.0.4
##### SUMMARY

Since role update earlier this week, bigip_command module always fails with 
```
AttributeError: 'module' object has no attribute 'ANSIBLE_CONNECTION_PATH'
```
Role was updated again from master within the last hour.

##### STEPS TO REPRODUCE

```
(See GIST https://gist.github.com/C0missar/38feb6c05c061f24d101ae18ba655372)

```

##### EXPECTED RESULTS

The command "tmsh modify auth user admin password admin shell bash" would be executed on the remote host.
##### ACTUAL RESULTS

```
(See GIST https://gist.github.com/C0missar/38feb6c05c061f24d101ae18ba655372)
AttributeError: 'module' object has no attribute 'ANSIBLE_CONNECTION_PATH'

```

**Comment by focrensh** [comment]
FMFA-225 opened for internal tracking.

**Comment by wojtek0806** [comment]
what is the Ansible controller OS?

**Comment by wojtek0806** [comment]
i have looked into this a bit, waiting for Ansible answer before I can provide feedback further

**Comment by wojtek0806** [comment]
spoke to some folks at Ansible, and this is a bug in Ansible, I am opening issue in the core now, will reference this one. Not much we can do here for now.

**Comment by wojtek0806** [comment]
once this is fixed I will probably ask for backport to 2.8 and 2.7, not guarantees for now. If anything changes we will reopen

**Comment by wojtek0806** [comment]
ok i got some good news and bad news, good news this is not a bug more like a version discrepancy, the bad news is that you need to upgrade to version 2.8 for this to work. I will be updating the role to require 2.8 installed after it is released on 09/05

**Comment by C0missar** [comment]
So why has it been working all this time on 2.7?  I’m sure that what broke it is my updating Ansible a few weeks back – I corrupted my installation and rebuilt everything from scratch.  Was there a change, or a particular version I could/should go back to?

**Comment by C0missar** [comment]
Silly question.  I was on Ansible 2.7.1 before, and now I’m on 2.7.10.  I didn’t notice the 0 and thought I was still on the same version.  I’ll try a rollback, but I’d like to understand the version discrepancy and why it worked on the older version.

Thanks,
Stan

From: Stanly E Ward
Sent: Tuesday, April 30, 2019 3:11 PM
To: F5Networks/f5-ansible <reply@reply.github.com>
Subject: RE: [EXTERNAL] Re: [F5Networks/f5-ansible] bigip_command module fails with AttributeError: 'module' object has no attribute 'ANSIBLE_CONNECTION_PATH' (#1302)

So why has it been working all this time on 2.7?  I’m sure that what broke it is my updating Ansible a few weeks back – I corrupted my installation and rebuilt everything from scratch.  Was there a change, or a particular version I could/should go back to?

**Comment by wojtek0806** [comment]
unfortunately you cannot do that, the action plugins that are used for SSH connection has been updated in our repository to work with version 2.8. Your best bet is not to use the role for that particular play and just use standard ansible modules that come with 2.7.
